LibInt.fs update.
darklang/dark pull request #2868
Opened 2020-11-19 06:57 UTC by Athinanarof

## What is the problem/goal being addressed?

## What is the solution to this problem?

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*
I'm adapting old LibInt Ocalm functions to F#.

## How are you sure this works/how was this tested?
I tested each function by using the unit test.

## What is the reversion plan if this fails after shipping?
I can always revert these changes, I will ask Paul if there is information related to this that I need to be aware of.

## Has this information been included in the comments?
No, I'm not sure where those comments need to be, but I will add them as soon as I know where those need to be.

2020-11-19 22:25 UTC, pbiggar requested changes
This looks great, thanks! There's a bunch of small things in the comments that are applicable to most of the tests (esp that we don't need warnings for strings in most cases)

2020-11-19 22:25 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibInt.fs
> +      ; deprecated = ReplacedBy(fn "" "" 0) }
Can you fill in the names of the replacement functions for deprecated ones?
```suggestion
      ; deprecated = ReplacedBy(fn "Int" "random" 1) }
```

2020-11-19 22:25 UTC, pbiggar commented on fsharp-backend/tests/testfiles/int.tests
> +
I think you could test `Int::random_v0` like this:

```
List.range 1 100 |> List.map (\i -> Int.random 0 2) |> List.all (\i ->  i <= 1 && i >= 0) = true
```

2020-11-23 05:11 UTC, Athinanarof commented on fsharp-backend/tests/testfiles/int.tests
> +Int.sqrt_v0 100 = 10.0
It is returning a DFloat 9.949874371, should we return a DInt?

2020-11-23 23:20 UTC, pbiggar commented on fsharp-backend/tests/testfiles/int.tests
> +Int.sqrt_v0 100 = 10.0
Oh, it's supposed to return a float! Ok, that's fine, thanks.

2020-11-23 23:23 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibInt.fs
>            | _, [ _; DStr _ as a ] ->
Can you switch to `DStr a` rather than `DStr _ as a`? Otherwise the error message will say `DStr "string"` in it.

2020-11-23 23:26 UTC, pbiggar commented
Looking good. There's still two unresolved comments; ready to merge after that.

2020-11-24 23:08 UTC, merged

2020-11-24 23:09 UTC, pbiggar commented
Great, thank you!

As a followup can you:
- add an infix operator for Int::subtract_v0
- add a [test for Int::random](https://github.com/darklang/dark/pull/2868#discussion_r527244547)