Backend
darklang/dark pull request #2873
Opened 2020-11-25 22:15 UTC by Athinanarof

## What is the problem/goal being addressed?
Translate some functions needed to create a random test case.

## What is the solution to this problem?
While creating the test case suggested for the random function, I worked on some related functions: range, map, and bool.and.
I made small corrections to Bool.fs and formatted it; test cases are now running.
I translated the range and included test cases.
I added List.map test cases.
I made random_v0 inclusive of a.

## What are the changes here? How do they solve the problem, and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*

## How are you sure this works/how was this tested?
Test cases are running and returning the correct results.

## What is the reversion plan if this fails after shipping?
Updates can always be reverted.

## Has this information been included in the comments?

2020-11-26 00:01 UTC, pbiggar requested changes
Looks great. There's a handful of changes to make, but this is coming along nicely! 😊

2020-11-26 00:01 UTC, pbiggar commented on fsharp-backend/tests/testfiles/int.tests
> +List.map_v0 (List.map_v0 (List.range_v0 1 5) (fun x -> Int.random_v0 1 2)) (fun x -> Bool.and_v0 (Int.greaterThanOrEqualTo_v0 x 0) (Int.lessThanOrEqualTo_v0 x 1)) = [true; true; true; true; true]
```suggestion
List.map_v0 (List.map_v0 (List.range_v0 1 100) (fun x -> Int.random_v0 1 2)) (fun x -> Bool.and_v0 (Int.greaterThanOrEqualTo_v0 x 0) (Int.lessThanOrEqualTo_v0 x 1)) = [true; true; true; true; true]
```

2020-11-26 00:01 UTC, pbiggar commented
Note there are merge conflicts too!

2020-11-28 22:46 UTC, Athinanarof commented on fsharp-backend/src/LibExecution/StdLib/LibInt.fs
> +            Value(DInt(a + (Runtime.random.Next((b - a) |> int) |> bigint)))
Yes, that was happening with random_v0 and v1. I have removed both comments and adjusted v1.

2020-12-03 14:36 UTC, merged