Libfloat fs
darklang/dark pull request #2936
Opened 2021-02-08 03:42 UTC by Athinanarof

## What is the problem/goal being addressed?
Implement LibFloat functions.
## What is the solution to this problem?
Functions translated.

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*

## How are you sure this works/how was this tested?
Unit test included for each function, only still pending support nan in tests.

## What is the reversion plan if this fails after shipping?
Revert changes

## Has this information been included in the comments?

2021-02-08 03:43 UTC, Athinanarof commented
Hi @pbiggar here is a new PR :)

2021-02-08 16:13 UTC, pbiggar requested changes
Thanks! A few fixes and we should be good to go. Can you add a test for `-0.0` and `0.0` for all functions too?

2021-02-08 16:13 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibFloat.fs
> +  [ { name = fn "Float" "ceiling" 0
The old function had 2 names: "Float::ceiling" and "Float::roundUp" (its been mangled a bit by some regexes). So you need to add a function that does the same thing called Float::roundup_v0.

2021-02-08 16:13 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibFloat.fs
> +    { name = fn "Float" "floor" 0
Needs a "Float::roundDown_v0" too

2021-02-08 16:13 UTC, pbiggar commented on fsharp-backend/tests/testfiles/float.tests
> +Float.ceiling_v0 0000000.1 = 1
This seems like the wrong answer.

2021-02-08 16:13 UTC, pbiggar commented on fsharp-backend/tests/testfiles/float.tests
> +Float.negate_v0 5.6 = -5.6
Can you add a test for 0 and -0?

2021-02-17 00:29 UTC, pbiggar commented
Merged in https://github.com/darklang/dark/pull/2945, thanks!

I didn't do the fixes, will do them in my branch.

2021-02-17 00:58 UTC, closed without merging