Libfloat.fs
darklang/dark pull request #2955
Opened 2021-02-23 08:16 UTC by Athinanarof

## What is the problem/goal being addressed?
Libfloat functions ported.

## What is the solution to this problem?
Functions implemented.

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*

## How are you sure this works/how was this tested?
Unit test included.

## What is the reversion plan if this fails after shipping?
Revert changes

## Has this information been included in the comments?

2021-02-23 08:17 UTC, Athinanarof commented
Hi @pbiggar, can you take a look at this PR please :).

2021-02-23 15:14 UTC, pbiggar requested changes
Looks good, thanks!

I'm not sure what's going on with Math.Clamp though.

2021-02-23 15:14 UTC, pbiggar commented on fsharp-backend/tests/testfiles/float.tests
> +Float.clamp_v0 (1.0 / 0.0) -1.0 0.5 = 0.5
You can use NaN instead of dividing by zero here.

2021-02-23 15:14 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibFloat.fs
> +            ( match Single.TryParse(Math.Clamp(v, min, max), output) with
What is this for? Math.Clamp seems to return a double, and parsing it doesn't make sense. I'm also unclear on why we'd use Single instead of Double.

2021-02-27 00:37 UTC, pbiggar commented
Copied into #2958

2021-02-27 00:37 UTC, closed without merging