Dict functions
darklang/dark pull request #3009
Opened 2021-04-12 14:48 UTC by mariajdab

## What is the problem/goal being addressed?
Added functions to `LibDict `and the test cases in `dict.test`
## What is the solution to this problem?
Added functions to `LibDict `and the test cases in `dict.test`

## How are you sure this works/how was this tested?
Test cases passed

## Has this information been included in the comments?
Yes

2021-04-12 21:32 UTC, pbiggar requested changes
Looks great! Should be good to go with some minor changes.

2021-04-12 21:32 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibDict.fs
> +              | DList [DStr k; value] when Map.containsKey k acc -> Map.remove k acc |> Map.add k value
This condition is not needed, as `add` will overwrite an existing key

2021-04-12 21:32 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibDict.fs
> +              | _ -> Errors.throw "All list items must be `[key, value]`"
There's an error condition in the old code, where if there is a DIncomplete, DErorrRail or DError found, it is returned. You can replicate that here using `Errors.foundFakeDval`. (Please add a test for it too, if possible)

2021-04-12 21:32 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibDict.fs
> +              | DList [k; value] -> Errors.throw(Errors.argumentWasnt "String`s" "key" k)
```suggestion
              | DList [k; value] -> Errors.throw(Errors.argumentWasnt "a string" "key" k)
```

2021-04-12 21:32 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibDict.fs
> +              | Some acc, DList [k; value] -> Errors.throw(Errors.argumentWasnt "String`s" "key" k)
```suggestion
              | Some acc, DList [k; value] -> Errors.throw(Errors.argumentWasnt "a string" "key" k)
```

2021-04-12 21:32 UTC, pbiggar commented on fsharp-backend/tests/testfiles/dict.tests
> +Dict.fromListOverwritingDuplicates_v0 [[1;1]] = Test.typeError_v0 "Expected the argument `key` to be String`s, but it was `1`" // FSHARPONLY
Can you add an equivalent OCAMLONLY test?

2021-04-12 21:32 UTC, pbiggar commented on fsharp-backend/tests/testfiles/dict.tests
> +Dict.fromList_v0 [[1;1]] = Test.typeError_v0 "Expected the argument `key` to be String`s, but it was `1`" // FSHARPONLY
Can you add an equivalent OCAMLONLY test?

2021-04-12 21:41 UTC, mariajdab commented
Perfect, I will add the suggestions.

2021-04-13 01:11 UTC, pbiggar approved these changes

2021-04-13 01:11 UTC, pbiggar commented
Great, thank you! Nice job.

2021-04-13 01:12 UTC, merged