Origin/daniela/liblist migration
darklang/dark pull request #3096
Opened 2021-06-23 21:10 UTC by danicampagna

## What is the problem/goal being addressed?
Continue with the migration of the functions written in OCaml to F#, in this case those of the `LibList.fs` class

## What is the solution to this problem?
Functions previously in OCaml, migrated to F#

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*

## How are you sure this works/how was this tested?
Tests passed and I added some aditional tests to try different results. 

## What is the reversion plan if this fails after shipping?

## Has this information been included in the comments?

2021-06-25 02:31 UTC, pbiggar requested changes
Nice job!

Apart from the small signature change, can you reformat using the `script/format` script and rebase the changes so that we don't have any formatting changes anymore? Thanks!

2021-06-25 02:31 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibList.fs
> +          Param.makeWithArgs "f" (TFn([ varA ], TBool)) "" [ "val" ] ]
The `TBool` here should be a `TOption varB`

2021-06-25 02:31 UTC, pbiggar commented on fsharp-backend/src/LibExecution/StdLib/LibList.fs
> +      returnType = TList varA
This should be a `TList varB`

2021-06-28 18:35 UTC, danicampagna commented
I used the `script/format` script and cherry-picked the commits in PR [#3100](https://github.com/darklang/dark/pull/3100)

2021-07-05 00:48 UTC, closed without merging