Backfill string tests
darklang/dark pull request #3541
Opened 2022-03-06 20:51 UTC by StachuDotNet

## What is the problem/goal being addressed?
Several String lib functions are un-tested or undertested.

## What is the solution to this problem?
Add tests.

2022-03-06 20:51 UTC, StachuDotNet commented on fsharp-backend/tests/testfiles/string.tests
> +String.fromChar_v1 ("1" |> String.toChar_v1) = Test.typeError "String::fromChar_v1 was called with the wrong type to parameter: c" // OCAMLONLY
Is this the best we can do?

2022-03-07 18:03 UTC, pbiggar requested changes
Looks good.

Can you also do some unicode tests here? Given that Dark is supposed to support characters are EGCs (extended grapheme pairs), this would be a key place to test that.

2022-03-08 15:49 UTC, pbiggar commented
You might need `open Types.RuntimeT`?

2022-03-08 15:59 UTC, StachuDotNet commented
> You might need `open Types.RuntimeT`?

Great, that unblocked that error, thanks.

2022-03-08 16:56 UTC, StachuDotNet commented
Somehow struggling to get `String.fromList_v1 [Test.toChar_v0 "a"]` working, I suspect because of the Option returned. My attempts to deconstruct in a way that both OCaml and F# like are failing.

Separately, I don't have good intuition to what "unicode tests" should be implemented here. Going to step away from this as I feel somehow stuck. Feel free to finish this up, or maybe we can pair for a few minutes, otherwise I'll circle back.

2022-03-09 00:04 UTC, merged