Add Bytes::base64Decode
darklang/dark pull request #3613
Opened 2022-03-22 03:17 UTC by mjibson

2022-03-22 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/darklang/dark?pullRequest=3613) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/darklang/dark?pullRequest=3613) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/darklang/dark?pullRequest=3613) it.</sub>

2022-03-22 03:19 UTC, mjibson commented
This is an F#-only implementation, and has failing and insufficient tests. They are currently producing things like:

```
expected: DResult (Error (DStr "Not a valid base64 string"))
  actual: DIncomplete SourceNone
```

and I thought it more prudent to open a PR with readable code (instead of Slack) to request help for this. I am unable to search or understand why this `DIncomplete` type is being produced.

2022-03-22 03:34 UTC, pbiggar commented
Tests by default are tested against both OCaml and F# implementations, and run against OCaml first. So the DIncomplete here is in the OCaml implementation, because there isn't an OCaml version of the function.

The solution is to add the comment ` // FSHARPONLY` at the end of the line, and that will ensure it is not run in the OCaml version.

2022-03-22 04:36 UTC, mjibson commented
Got a bit further. I'm not able to get the bytes literal syntax to work. I tried a bunch, all in the current revision. Example failure:

```
[04:33:12 ERR] tests.LibExecution.All files.Tests from bytes.tests..FSHARPONLY (line 16) (Bytes.base64Decode_v0 "Kw" = (DBytes [|43uy|])) errored in 00:00:00.0140000 <Expecto>
Expecto.AssertException: .
expected:
("Prelude+InternalException: Unsupported expression
```

2022-03-22 15:01 UTC, pbiggar commented
Apologies, I led you astray. When referring to `[| 45uy |]`, that's actually F# syntax, not Dark.

I can't think of a good way to create bytes that exists right now, except from UTF8. However, it would probably be easy to create one. You could make a function called `Test::asBytes_v0` in LibTest.fs, and call it like so `Test.asBytes_v0 [45;6;72]`.

2022-03-23 04:38 UTC, mjibson commented
RFAL

2022-03-23 14:59 UTC, pbiggar commented
Thanks! 👀

2022-05-23 13:36 UTC, pbiggar commented
It occurred to me to check that there were tests here for both types of base64, as this supports both. I think some of the tests touch on it but we should make those explicit.

Still planning to merge this once we've stopped using the OCaml execution engine entirely. Any day now...

2022-06-24 01:47 UTC, StachuDotNet commented
@pbiggar I think we can do this?

2022-06-24 12:51 UTC, pbiggar commented
Yes!

2022-06-24 15:48 UTC, StachuDotNet commented
I made a mistake in the conflict-resolution; resolving.

2022-06-24 16:55 UTC, pbiggar commented on fsharp-backend/tests/TestUtils/LibTest.fs
> +    { name = fn "Test" "asBytes" 0
There should be two lines between separate function definitions

2022-06-24 16:55 UTC, pbiggar commented on fsharp-backend/src/LibExecutionStdLib/LibBytes.fs
> +
There should be two lines between separate function definitions

2022-06-24 16:55 UTC, pbiggar commented on fsharp-backend/tests/testfiles/bytes.tests
> +Bytes.base64Decode_v0 "random string" = Error "Not a valid base64 string" // FSHARPONLY
We can remove the FSHARPONLY annotations now

2022-06-24 16:55 UTC, pbiggar commented on fsharp-backend/tests/TestUtils/LibTest.fs
> +      deprecated = NotDeprecated }
There should be two lines between separate function definitions

2022-06-24 16:56 UTC, pbiggar requested changes
A few small changes left and we can merge

2022-06-27 16:55 UTC, merged

2022-06-27 16:55 UTC, pbiggar commented
Great, thanks for pushing this over the line @StachuDotNet.

Thanks for the contribution @mjibson!

2022-06-27 18:46 UTC, mjibson commented
Yay, thanks for the followup.