Allow processing the only correct expressions into a pipeline.
darklang/dark pull request #4854
Opened 2023-04-16 23:18 UTC by ditansu

Only correct expressions processing in a pipeline.  
Support as minimum:
```fsharp
  | EInfix of id * Infix * Expr * Expr
  | ELambda of id * List<id * string> * Expr
  | EVariable of id * string
  | EFnCall of id * FQFnName.T * typeArgs : List<TypeReference> * args : List<Expr>
```
The all mapping from `PT.EPipeExpr` to `RT.Expr` (mostly in `FApply`) have to be in `ProgramTypesToRuntimeTypes`

Previous attempts:
https://github.com/darklang/dark/pull/4848
https://github.com/darklang/dark/pull/4814
https://github.com/darklang/dark/pull/4803

2023-04-16 23:21 UTC, ditansu commented
@pbiggar I've committed tests and mark all failed cases by` // TODO: actual: ... `. Please choose which ones have to be success as result of this PR.

2023-04-17 16:27 UTC, pbiggar reviewed
Thanks for this! I think I got all the categories, but let me know if there's any ambiguity.

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // |> List.length_v0)) = 5 // TODO: actual:  DError(SourceNone,"Attempting to access a field of something that isn't a record or dict, (it's a Dict).")
supported

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // (3 |> Ok()) = Ok 3 // TODO: actual: DError (SourceNone, "Expected a function value, got something else: Ok unit")
support later

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // (3 |> Ok()) = Ok 3 // TODO: actual: DError (SourceNone, "Expected a function value, got something else: Ok unit")
no parens though

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // |> x
support now

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  (let x = Just(3) in
Support now

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  (let x = fun a -> Result.withDefault_v0 a 1 in
Support now

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // (let x = fun a -> Option.withDefault_v0 a 3 in
Support later (thouhg will always fail as `Nothing` doesn't take a parameter).

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  (let x = fun x -> Option.andThen_v0 (Just x) (fun x -> Just (1 + x)) in
Support now

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // |> Just()
Support later (no parens after `Just` though)

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // |> 57
This should become a parse error

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  |> (2,2)
This should be a parse error

2023-04-17 16:27 UTC, pbiggar commented on backend/testfiles/execution/language.tests
> +  // |> (2,2)
Parse error

2023-04-21 23:04 UTC, ditansu commented
hm, on my laptop all tests passed successfully

2023-04-24 22:31 UTC, ditansu commented
@pbiggar hey! The most test cases were solved by transformation from `EPipeExpr` to `Expr` as it was required. I guess this PE are ready to review.

2023-04-24 22:59 UTC, pbiggar requested changes
Thanks for this.

This doesn't quite feel right to me. I think the right solution wouldn't have:

- PT.Pipe.fromExpr
- PT.Pipe.toExpr
- PT.EForbiddenExpr
- PT.EPipeTarget

and I think you're missing:
- PipeExpr in ClientProgramTypes.Expr
- PipeExpr in SerializedTypes.Expr

Also, I think you've added back things that have been removed:
- DDict handling in EFieldAccess
- ClientTypes2ExecutionTypes/ProgramTypes.fs

2023-04-25 23:46 UTC, ditansu commented
> Thanks for this.

@pbiggar thanks for answer! 

> This doesn't quite feel right to me. I think the right solution wouldn't have:
> 
> * PT.Pipe.fromExpr
> * PT.Pipe.toExpr

Ok, but how you offer to process [this case](https://github.com/darklang/dark/blob/3aeb3d9922acd02734bea36a64d5bef9d6bed1a9/backend/src/LibExecution/ProgramTypesAst.fs#L24) in `traverse`? We can apply `f` only for `Expr` and `f` return `Expr` so first we need to translate from `PipeExpr` to `Expr` and next we need to back translate from `Expr` to `PipeExpr`. Is it correct?  If yes, and you know another way (without bi-direction translate) please show me.    

> * PT.EForbiddenExpr
> * PT.EPipeTarget

Ok, probably I know how to avoid using it. 


> and I think you're missing:
> 
> * PipeExpr in ClientProgramTypes.Expr
> * PipeExpr in SerializedTypes.Expr

Yeah, you are right.  

> Also, I think you've added back things that have been removed:
> 
> * DDict handling in EFieldAccess

I tried to pass this test case 

```fsharp
  // field access
  (let x = { y = { z = { a = [1;2;3;4;5] }}} in
  (x.y.z.a
  |> List.length_v0)) = 5
```
```bash
expected:
DInt 5L
  actual:
DError
  (SourceNone,
   "Attempting to access a field of something that isn't a record or dict, (it's a Dict).")",
```

by code from the main branch and this case faulting with error which show that this `x` processed in `EFieldAccess` case, but yes it was wrong solution, I try to fix it another way.

> * ClientTypes2ExecutionTypes/ProgramTypes.fs

hm, really strange how I did it,  my bad, I'll fix it.

2023-04-26 16:55 UTC, pbiggar commented
> > Thanks for this.
> 
> @pbiggar thanks for answer!
> 
> > This doesn't quite feel right to me. I think the right solution wouldn't have:
> > 
> > * PT.Pipe.fromExpr
> > * PT.Pipe.toExpr
> 
> Ok, but how you offer to process [this case](https://github.com/darklang/dark/blob/3aeb3d9922acd02734bea36a64d5bef9d6bed1a9/backend/src/LibExecution/ProgramTypesAst.fs#L24) in `traverse`? We can apply `f` only for `Expr` and `f` return `Expr` so first we need to translate from `PipeExpr` to `Expr` and next we need to back translate from `Expr` to `PipeExpr`. Is it correct? If yes, and you know another way (without bi-direction translate) please show me.

We don't need to process the PipeExpr using traverse, just the Exprs within it. I'm currently redoing `traverse` as we speak though - each thing that's not an Expr will have its own fn argument to manipulate the AST (so letPatternFn, matchPatternFn, etc, and then pipeExprFn).


> > * DDict handling in EFieldAccess
> 
> I tried to pass this test case
> 
> ```fsharp
>   // field access
>   (let x = { y = { z = { a = [1;2;3;4;5] }}} in
>   (x.y.z.a
>   |> List.length_v0)) = 5
> ```

What we do now is require a Type name for each record. And the type must exist. So you can do


> ```fsharp
>   // field access
>   type Z = { a : List<Int> }
>   type Y = { z : Z }
>   type X = { y : Y }
>   (let x = X { y = Y { z = Z { a = [1;2;3;4;5] }}} in
>   (x.y.z.a
>   |> List.length_v0)) = 5
> ```

2023-05-01 00:44 UTC, ditansu commented
@pbiggar please review when you'll have time.

2023-05-01 03:46 UTC, pbiggar reviewed
Looks really great! I'll give it a proper look tomorrow and I think we might be able to merge.

2023-05-01 16:52 UTC, pbiggar requested changes
This looks great! I cleaned up the PR a bit (there was lots of rebase and merge churn), and fixed up some test formatting.

I think we can get this merged with a few small changes. Thanks again!

2023-05-01 16:52 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +        | PT.EPipeEnum (id, typeName, caseName, _) ->
We're not using existing arguments here in the Enum

2023-05-01 16:52 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +          RT.EFieldAccess(id, toRT obj, fieldname) |> applyFn
I don't think there's any tests for EFieldAccess

2023-05-01 16:52 UTC, pbiggar commented on backend/src/Parser/ProgramTypes.fs
> +              | PT.EPipeFnCall (id, PT.FQFnName.User name, typeArgs, args) ->
This should be handled in `preTraversal`

2023-05-01 16:52 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +          RT.EFieldAccess(id, toRT obj, fieldname) |> applyFn
I think it would be better to remove EPipeField access for now. We don't have parsing or tests and it's a new feature.

2023-05-01 16:52 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +        | PT.EPipeEnum (id, typeName, caseName, _) ->
A test for this would be good too

2023-05-01 16:52 UTC, pbiggar commented on backend/src/Parser/ProgramTypes.fs
> +  let rec completeParse
This shouldn't need to be `rec` if we traverse properly in ProgramTypesAst

2023-05-01 16:52 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesAst.fs
> +  | EPipe (id, expr1, expr2, exprs) -> EPipe(id, f expr1, expr2, exprs)
This would be very similar to `preTraversalLetPattern` above

2023-05-01 16:52 UTC, pbiggar commented on backend/src/Parser/ProgramTypes.fs
> +    // PT.EPipe(id, other, synToPipeExpr arg, [])
I'm not sure why this comment is here?

2023-05-02 14:55 UTC, pbiggar requested changes
This looks fantastic!

I think it's worth fixing the parser pre-merge so that we can git rid of the hack in ProgramTypesToRuntimeTypes.

2023-05-02 14:55 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +            |> List.filter (function
I think this is an artifact of the parser or maybe just the tests.

For the test `(3 |> Ok()) = Ok 3`, we should actually write this test as `(3 |> Ok) = Ok 3`. I think that doesn't work out of the box though, and I suspect you need to update the parser to make it work.

The parser is a little finicky, let me know if you'd like me to take a shot at it.

2023-05-03 14:05 UTC, pbiggar requested changes
Looking great, thanks! A few more small fixes and we should be good to go.

2023-05-03 14:05 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +          let fields' = List.map toRT fields @ [ prev ]
This should go in the front, not the back, to match how pipes work elsewhere.

Maybe a test for this too (perhaps an enum with 3 params)

2023-05-03 14:05 UTC, pbiggar commented on backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
> +        | PT.EPipeVariable (id, name) -> RT.EVariable(id, name) |> applyFn
Since this is the only place using applyFn, we should inline it.

2023-05-04 17:37 UTC, merged

2023-05-04 17:38 UTC, pbiggar commented
Great, thanks again!