Migrate runtime errors and handling to Dark
darklang/dark pull request #5021
Opened 2023-08-11 15:21 UTC by StachuDotNet

Changelog:

```
Area of change
- details
```

2023-08-13 14:58 UTC, pbiggar commented
fyi working on rebasing this off new main

2023-08-14 01:26 UTC, pbiggar commented
Pushed a merge commit. It compiles but I'm not super confident I didn't reintroduce some things we already fixed.

2023-08-24 14:37 UTC, StachuDotNet commented
This PR is in a pretty good place - builds, tests pass, and I've done a full once-through reading the PR's changes.
Here are my remaining TODOs:

- [ ] remove the unncesarry (?) units from the RT.PackageManager and impls
- [ ] copy Types.fs for later usage; delete it
- [ ] de-duplicate the Decode in RuntimeTypestoDarkTypes
- [ ] delete more in the Errors.fs file?
- [ ] update Interpreter to use ToRuntimeError from another file
- [ ] fix the ugly RunAsyncronously in LibExecution.Tests.fs
- [ ] deal with "// TODO we should not have an RTE inside of an Error differently" in Interpreter
- [ ] ensure BwdDangerServer and CanvasHack is still OK
- [ ] ensure CLI is still OK, and can reference packages
    - [ ] including when calling upon files on disk
- [ ] review NameResolutionError.fs' "fromRuntimeError" - [ ] I think it needs adjustment
- [ ] get Cli to return RTE; call toString on the RTE and sure all is OK
- [ ] get LocalExec to return RTE; call toString on the RTE and sure all is OK
- [ ] adjust "allowError" field of NameResolver
    - [ ] fix // comment
    - [ ] make it a ///
    - [ ] rename the field
- [ ] fail local-exec if 500 on POST (it's nearly done...)
- [ ] remove some ()s in LocalExec
    - [ ] and debuGs

2023-08-25 02:13 UTC, StachuDotNet commented
remaining TODOs before merging:
- [ ] update `reload-packages` script to wait for BwdDangerServer to be running when [see commented out code in that file]
- [ ] get the "push packages to the `dark-packages` canvas" half of `reload-packages` working
  - when I go to run this, I face a runtime error raised by StdLib.../Json.fs, seen in `packages-canvas.log` - not sure why, but I think it's in `local-exec.dark`'s `loadPackageFileIntoDarkCanvas`
  - a reasonable way to check that things are working is going to http://dark-packages.dlio.localhost:11003/stats and seeing non-0 numbers
- [ ] make sure we haven't broken `Cli` somehow - especially, running scripts that reference package things
  - this can't be tested until the `reload-packages` thing works, since `Cli` uses the `dark-packages`-canvas-based package manager

2023-08-27 17:59 UTC, pbiggar requested changes
Looks great!!

All these comments were TODOs to myself to try and get merged, apologies if they were short/unclear.

2023-08-27 17:59 UTC, pbiggar commented on backend/testfiles/execution/language/einfix.dark
> +  "Int.add's 2nd argument (`b`) should be an Int. However, an Bool (true) was passed instead.\n\nExpected: (b: Int)\nActual: an Bool: true"
`An bool` is wrong

2023-08-27 17:59 UTC, pbiggar commented on backend/tests/Tests/LibExecution.Tests.fs
> +      // CLEANUP consider not doing the toErrorMessage call
This is a bit iffy - look closely

2023-08-27 17:59 UTC, pbiggar commented on backend/tests/Tests/LibExecution.Tests.fs
> +            // CLEANUP TODO BAD: I got stuck in Async hell and abandoned here
Fix

2023-08-27 17:59 UTC, pbiggar commented on backend/testfiles/execution/language/type-alias.dark
> +  "Something's `ID` field should be an String. However, an Int (2) was passed instead.\n\nExpected: ({ ID: Id; ... })\nActual: an Int: 2"
"a" -> "an"

2023-08-28 02:56 UTC, pbiggar commented
I checked the TODOs I think are done, and marked resolved things that feel resolved. I think this could probably be merged in the current state.

2023-08-28 13:26 UTC, StachuDotNet commented on backend/src/LibExecution/Execution.fs
> +let runtimeErrorToString
ah, smart to extract this to a fn!

2023-08-28 13:33 UTC, StachuDotNet commented on backend/src/LibExecution/RuntimeTypesToDarkTypes.fs
> +// Note: doesn't actually exist at this point
I'm not sure what this comment is referring to?

2023-08-28 13:43 UTC, StachuDotNet commented on backend/src/StdLibCliHost/Libs/Cli.fs
> +                        |> LibExecution.DvalReprDeveloper.toRepr
Maybe we should use the new `runtimeErrorToString` here?

2023-08-28 13:44 UTC, StachuDotNet commented on backend/src/StdLibExecution/Libs/Json.fs
> +              (dval, typ, LibExecution.DvalReprDeveloper.dvalTypeName dval)
TODO: remove this `debuG` before merging, ideally - I haven't tested yet to see if this is fixed

2023-08-28 13:46 UTC, StachuDotNet commented on backend/src/StdLibExecution/Libs/String.fs
> +    { name = fn "head" 0
fwiw this could be a package fn, I think (toList, List.head) - or is it better this way for perf reasons or something?

2023-08-28 14:55 UTC, StachuDotNet commented
[ ] backfill RT2DT roundtripping tests

2023-08-28 19:11 UTC, merged