WIP: Lambda arg destructuring
darklang/dark pull request #5025
Opened 2023-08-14 23:39 UTC by ditansu

Lambda argument **destructuring** support
Like that ` fun (num, str) ->...` in example below

```fsharp
(let pairs = [(1, "one"); (2, "two"); (3, "three")] in
 let transformer = fun (num, str) -> $"{Int.toString num}:{str}" in
 List.map_v0 pairs transformer) = ["1:one"; "2:two"; "3:three"]
```

2023-08-19 22:32 UTC, ditansu commented
@pbiggar hey! Please review this PR. Is it right way to make a lambda args destructuring in the interpreter? What else cases need to handle - e.g. args list destrucructuring?

2023-08-22 15:40 UTC, StachuDotNet commented
It's neat you were able to tackle this without introducing any new language constructs - I expected we'd end up adding a `LambdaArgPattern` or re-use the `LetPattern` in the lambda to support this functionality. Maybe this is fine, though? I'll defer to the requested Paul to review this :)

2023-08-23 20:18 UTC, pbiggar requested changes
I think we want to reuse LetPattern here. Tuples are single values so they should destructure using a tuple pattern:

```
List.map (fun (k, v) -> k ++ v) [("1", "2")]
```

2023-08-23 20:18 UTC, pbiggar commented on backend/testfiles/execution/language/elambda.dark
> + let transformer = fun num str -> $"{Int.toString num}:{str}" in
```suggestion
 let transformer = fun (num, str) -> $"{Int.toString num}:{str}" in
```

2023-08-23 20:18 UTC, pbiggar commented on backend/testfiles/execution/language/elambda.dark
> +   fun num str flag ->
```suggestion
   fun (num, str, flag) ->
```

2023-08-26 00:12 UTC, pbiggar commented on backend/src/LibExecution/Interpreter.fs
> +    | [ DTuple(_, _, rest) ] when
Can the destructuring be integrated with ELet destructuring and using the same code? It's not just about allowing tuples in lambdas, it's about having `let (x, y) =` do the same thing as `fun (x,y) -> `

2023-08-26 00:12 UTC, pbiggar requested changes
Can the destructuring be integrated with ELet destructuring and using the same code? It's not just about allowing tuples in lambdas, it's about having let (x, y) = do the same thing as fun (x,y) ->

2023-09-30 16:30 UTC, ditansu commented
> Can the destructuring be integrated with ELet destructuring and using the same code? It's not just about allowing tuples in lambdas, it's about having let (x, y) = do the same thing as fun (x,y) ->

@pbiggar so does it mean we have to change the `ELambda` definition on this:
```fsharp
ELambda of id * args: NEList<LetPattern> * body: Expr
```
in `/home/dark/app/backend/src/LibParser/WrittenTypes.fs`?

2023-09-30 17:51 UTC, pbiggar commented
> > Can the destructuring be integrated with ELet destructuring and using the same code? It's not just about allowing tuples in lambdas, it's about having let (x, y) = do the same thing as fun (x,y) ->
> 
> @pbiggar so does it mean we have to change the `ELambda` definition on this:
> 
> ```fsharp
> ELambda of id * args: NEList<LetPattern> * body: Expr
> ```
> 
> in `/home/dark/app/backend/src/LibParser/WrittenTypes.fs`?

Yes, that looks like it.

2023-10-03 21:10 UTC, ditansu commented
too hard to sync

2023-10-03 21:10 UTC, ditansu commented
too hard to sync

2023-10-03 21:10 UTC, closed without merging