Implement integer conversion functions and add corresponding tests
darklang/dark pull request #5155
Opened 2023-11-17 14:41 UTC by OceanOak

Changelog:

```
Area of change
- Implement integer conversion functions and add corresponding tests
```

**Int8:** fromUInt8, fromInt16, fromUInt16, fromInt32, fromUInt32, fromInt64, fromUInt64, fromInt128, fromUInt128
**UInt8:** fromInt8, fromInt16, fromUInt16, fromInt32, fromUInt32, fromInt64, fromUInt64, fromInt128, fromUInt128
**Int16:** fromInt8, fromUInt8, fromUInt16, fromInt32, fromUInt32, fromInt64, fromUInt64, fromInt128, fromUInt128
**UInt16:** fromInt8, fromUInt8, fromInt16, fromInt32, fromUInt32, fromInt64, fromUInt64, fromInt128, fromUInt128
**Int32:** fromInt8, fromUInt8, fromInt16, fromInt16, fromUInt32, fromInt64, fromUInt64, fromInt128, fromUInt128
**UInt32:** fromInt8, fromUInt8, fromInt16, fromInt16, fromInt32, fromInt64, fromUInt64, fromInt128, fromUInt128
**Int64:** fromInt8, fromUInt8, fromInt16, fromInt16, fromInt32, fromUInt32, fromUInt64, fromInt128, fromUInt128
**UInt64:** fromInt8, fromUInt8, fromInt16, fromInt16, fromInt32, fromUInt32, fromInt64, fromInt128, fromUInt128
**Int128:** fromInt8, fromUInt8, fromInt16, fromInt16, fromInt32, fromUInt32, fromInt64, fromUInt64
**UInt128:** fromUInt8, fromUInt16, fromUInt32, fromUInt64

2023-11-17 16:51 UTC, OceanOak commented on backend/src/Prelude/Prelude.fs
> +module NumericLiteralQ =
I am not sure if this is the right place for these two modules, we need them in all Builtin (U)IntX files and in TestUtils. Please let me know if I should move them elsewhere

2023-11-20 14:09 UTC, pbiggar requested changes
I think there are some errors in the conversions. In particular, when going from type A which fully fits in type B (eg int16 to int32), we shouldn't need an option.

2023-11-20 18:09 UTC, pbiggar approved these changes
OK, this looks good!

2023-11-20 18:09 UTC, merged

2023-11-20 19:50 UTC, OceanOak commented on backend/testfiles/execution/stdlib/int8.dark
> +
Followup PR 
PACKAGE.Darklang.Stdlib.Int8.fromInt32_v0 (-129l) = PACKAGE.Darklang.Stdlib.Option.Option.None

2023-11-20 19:57 UTC, OceanOak commented on backend/testfiles/execution/stdlib/uint64.dark
> +  127UL
Followup PR add 
PACKAGE.Darklang.Stdlib.UInt64.fromInt8_v0 -128y = PACKAGE.Darklang.Stdlib.Option.Option.None