wip: self update
darklang/dark pull request #5276
Opened 2024-01-24 17:48 UTC by OceanOak

Changelog:

```
Area of change
- details
```

alternatively:

No changelog

## What is the problem/goal being addressed?

## What is the solution to this problem?

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*

## How are you sure this works/how was this tested?

## What is the reversion plan if this fails after shipping?

## Has this information been included in the comments?

2024-01-30 15:46 UTC, StachuDotNet commented on packages/darklang/cli/cli.dark
> +    // get list of releases from github api
```suggestion
    /// get tag of most recent release, from github api
    /// (i.e. `v0.0.19`)
```

2024-01-30 16:48 UTC, StachuDotNet commented on packages/darklang/cli/cli.dark
> +            arch.exitCode
I think it's worth tidying this up a bit to represent these unexpected things as Results -- it's easy to lose context of the fact that these strings might be some negative case. I think there are a few places here where this is relevant

2024-01-30 16:49 UTC, StachuDotNet requested changes
Overall, nice! I think it's worth
- using Results a bit more, to represent error situations
- probably extracting the functionality here to a sub-module (see adjacent `packageViewer.dark`) so all of the "self-update" stuff is one place

2024-01-31 16:41 UTC, OceanOak commented on packages/darklang/cli/selfUpdate.dark
> +        let localVersion = (getLocalVersion ()) |> Builtin.unwrap
Does using Builtin.unwrap here defeat the purpose of returning a result?

2024-01-31 17:39 UTC, StachuDotNet approved these changes
Great! Ready to merge when you are

2024-01-31 19:31 UTC, merged